# Generated by Django 2.2.16 on 2022-11-24 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_auto_20221124_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientwithamount',
            name='amount',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Количество'),
            preserve_default=False,
        ),
    ]
