# Generated by Django 2.2.16 on 2022-11-24 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_ingredientwithamount_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientwithamount',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.Ingredient', verbose_name='Ингредиент'),
        ),
    ]
