# Generated by Django 2.2.16 on 2022-11-26 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_auto_20221124_1154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientwithamount',
            options={'default_related_name': 'recipe_ingredients', 'ordering': ['-id'], 'verbose_name': 'Количество ингредиента', 'verbose_name_plural': 'Количество ингредиентов'},
        ),
        migrations.AlterField(
            model_name='ingredientwithamount',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='recipe.Ingredient', verbose_name='Ингредиент'),
        ),
    ]
