# Generated by Django 2.2.16 on 2022-11-26 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_auto_20221126_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientwithamount',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='recipe.Ingredient', verbose_name='Ингредиентs'),
        ),
    ]
