# Generated by Django 2.2.16 on 2022-11-26 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_auto_20221126_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientwithamount',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='recipe.Ingredient', verbose_name='Ингредиент'),
        ),
    ]
